<!DOCTYPE html>
<html>
<head>
    <title>first report</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2 class="text-capitalize">first report</h2>
                <p class='attribute'><strong>Start Time: </strong>2022-02-12 23:46:00</p>
                <p class='attribute'><strong>Duration: </strong>79.30 s</p>
                <p class='attribute'><strong>Summary: </strong>Total: 12, Pass: 0, Error: 12</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-10 col-md-10">
                <table class='table table-hover table-responsive'>
                    <thead>
                        <tr>
                            <th>__main__.FirstDdtCase</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_1___11xcvcxqq_com____asdfasxczv____xzc3354354____vcode____user_email_error____请输入有效的电子邮件地址______________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_2___12xcvcxqq_com____asdfasxczv____xzc3354355____vcode____user_email_error____请输入有效的电子邮件地址______________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_3___13xcvcx_qq_com____asdfasxczv____xzc3354356____vcode____user_email_error____请输入有效的电子邮件地址______________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_4_____________________________________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_5_____________________________________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_6_____________________________________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_7_____________________________________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_7_____________________________________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=98.0.4758.82)
Stacktrace:
Backtrace:
	Ordinal0 [0x01047AC3+2587331]
	Ordinal0 [0x00FDADD1+2141649]
	Ordinal0 [0x00ED3BB8+1063864]
	Ordinal0 [0x00EBC5D0+968144]
	Ordinal0 [0x00F1AE49+1355337]
	Ordinal0 [0x00F28192+1409426]
	Ordinal0 [0x00F184A6+1344678]
	Ordinal0 [0x00EF53F6+1201142]
	Ordinal0 [0x00EF62E6+1204966]
	GetHandleVerifier [0x011EDF22+1680738]
	GetHandleVerifier [0x012A0DBC+2413564]
	GetHandleVerifier [0x010DD151+563089]
	GetHandleVerifier [0x010DBF13+558419]
	Ordinal0 [0x00FE081E+2164766]
	Ordinal0 [0x00FE5508+2184456]
	Ordinal0 [0x00FE5650+2184784]
	Ordinal0 [0x00FEF5BC+2225596]
	BaseThreadInitThunk [0x75C96739+25]
	RtlGetFullPathName_UEx [0x77AE8AFF+1215]
	RtlGetFullPathName_UEx [0x77AE8ACD+1165]
</p><p style="color:maroon;">Traceback (most recent call last):
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 60, in tearDown
    self.driver.save_screenshot(img_path)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1342, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=98.0.4758.82)
Stacktrace:
Backtrace:
	Ordinal0 [0x01047AC3+2587331]
	Ordinal0 [0x00FDADD1+2141649]
	Ordinal0 [0x00ED3BB8+1063864]
	Ordinal0 [0x00EBC5D0+968144]
	Ordinal0 [0x00F1AE49+1355337]
	Ordinal0 [0x00F28192+1409426]
	Ordinal0 [0x00F184A6+1344678]
	Ordinal0 [0x00EF53F6+1201142]
	Ordinal0 [0x00EF62E6+1204966]
	GetHandleVerifier [0x011EDF22+1680738]
	GetHandleVerifier [0x012A0DBC+2413564]
	GetHandleVerifier [0x010DD151+563089]
	GetHandleVerifier [0x010DBF13+558419]
	Ordinal0 [0x00FE081E+2164766]
	Ordinal0 [0x00FE5508+2184456]
	Ordinal0 [0x00FE5650+2184784]
	Ordinal0 [0x00FEF5BC+2225596]
	BaseThreadInitThunk [0x75C96739+25]
	RtlGetFullPathName_UEx [0x77AE8AFF+1215]
	RtlGetFullPathName_UEx [0x77AE8ACD+1165]

</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_8_____________________________________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_8_____________________________________</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=98.0.4758.82)
Stacktrace:
Backtrace:
	Ordinal0 [0x01047AC3+2587331]
	Ordinal0 [0x00FDADD1+2141649]
	Ordinal0 [0x00ED3BB8+1063864]
	Ordinal0 [0x00EBC5D0+968144]
	Ordinal0 [0x00F1AE49+1355337]
	Ordinal0 [0x00F28192+1409426]
	Ordinal0 [0x00F184A6+1344678]
	Ordinal0 [0x00EF53F6+1201142]
	Ordinal0 [0x00EF62E6+1204966]
	GetHandleVerifier [0x011EDF22+1680738]
	GetHandleVerifier [0x012A0DBC+2413564]
	GetHandleVerifier [0x010DD151+563089]
	GetHandleVerifier [0x010DBF13+558419]
	Ordinal0 [0x00FE081E+2164766]
	Ordinal0 [0x00FE5508+2184456]
	Ordinal0 [0x00FE5650+2184784]
	Ordinal0 [0x00FEF5BC+2225596]
	BaseThreadInitThunk [0x75C96739+25]
	RtlGetFullPathName_UEx [0x77AE8AFF+1215]
	RtlGetFullPathName_UEx [0x77AE8ACD+1165]
</p><p style="color:maroon;">Traceback (most recent call last):
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 60, in tearDown
    self.driver.save_screenshot(img_path)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1342, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=98.0.4758.82)
Stacktrace:
Backtrace:
	Ordinal0 [0x01047AC3+2587331]
	Ordinal0 [0x00FDADD1+2141649]
	Ordinal0 [0x00ED3BB8+1063864]
	Ordinal0 [0x00EBC5D0+968144]
	Ordinal0 [0x00F1AE49+1355337]
	Ordinal0 [0x00F28192+1409426]
	Ordinal0 [0x00F184A6+1344678]
	Ordinal0 [0x00EF53F6+1201142]
	Ordinal0 [0x00EF62E6+1204966]
	GetHandleVerifier [0x011EDF22+1680738]
	GetHandleVerifier [0x012A0DBC+2413564]
	GetHandleVerifier [0x010DD151+563089]
	GetHandleVerifier [0x010DBF13+558419]
	Ordinal0 [0x00FE081E+2164766]
	Ordinal0 [0x00FE5508+2184456]
	Ordinal0 [0x00FE5650+2184784]
	Ordinal0 [0x00FEF5BC+2225596]
	BaseThreadInitThunk [0x75C96739+25]
	RtlGetFullPathName_UEx [0x77AE8AFF+1215]
	RtlGetFullPathName_UEx [0x77AE8ACD+1165]

</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_9___________________________________test__</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">ValueError: too many values to unpack (expected 6)</p><p style="color:maroon;">Traceback (most recent call last):
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\ddt.py", line 191, in wrapper
    return func(self, *args, **kwargs)
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 79, in test_reg_case
    email, username, password, vcode, assertCode, assertText=data
ValueError: too many values to unpack (expected 6)
</p>
                            </td>
                        </tr>
                        <tr class='warning'>
                            <td class="col-xs-10">test_reg_case_9___________________________________test__</td>
                            <td class="col-xs-1">
                                <span class="label label-warning" style="display:block;width:40px;">Error</span>
                            </td>
                            <td class="col-xs-1">
                                <button class="btn btn-default btn-xs">View</button>
                            </td>
                        </tr>
                        <tr style="display:none;">
                            <td class="col-xs-9" colspan="3"><p style="color:maroon;">NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=98.0.4758.82)
Stacktrace:
Backtrace:
	Ordinal0 [0x01047AC3+2587331]
	Ordinal0 [0x00FDADD1+2141649]
	Ordinal0 [0x00ED3BB8+1063864]
	Ordinal0 [0x00EBC5D0+968144]
	Ordinal0 [0x00F1AE49+1355337]
	Ordinal0 [0x00F28192+1409426]
	Ordinal0 [0x00F184A6+1344678]
	Ordinal0 [0x00EF53F6+1201142]
	Ordinal0 [0x00EF62E6+1204966]
	GetHandleVerifier [0x011EDF22+1680738]
	GetHandleVerifier [0x012A0DBC+2413564]
	GetHandleVerifier [0x010DD151+563089]
	GetHandleVerifier [0x010DBF13+558419]
	Ordinal0 [0x00FE081E+2164766]
	Ordinal0 [0x00FE5508+2184456]
	Ordinal0 [0x00FE5650+2184784]
	Ordinal0 [0x00FEF5BC+2225596]
	BaseThreadInitThunk [0x75C96739+25]
	RtlGetFullPathName_UEx [0x77AE8AFF+1215]
	RtlGetFullPathName_UEx [0x77AE8ACD+1165]
</p><p style="color:maroon;">Traceback (most recent call last):
  File "\\mac\Home\Documents\SeleniumPractice\case\first_ddt_case.py", line 60, in tearDown
    self.driver.save_screenshot(img_path)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1342, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1317, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1353, in get_screenshot_as_png
    return b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1365, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\caosheng\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=98.0.4758.82)
Stacktrace:
Backtrace:
	Ordinal0 [0x01047AC3+2587331]
	Ordinal0 [0x00FDADD1+2141649]
	Ordinal0 [0x00ED3BB8+1063864]
	Ordinal0 [0x00EBC5D0+968144]
	Ordinal0 [0x00F1AE49+1355337]
	Ordinal0 [0x00F28192+1409426]
	Ordinal0 [0x00F184A6+1344678]
	Ordinal0 [0x00EF53F6+1201142]
	Ordinal0 [0x00EF62E6+1204966]
	GetHandleVerifier [0x011EDF22+1680738]
	GetHandleVerifier [0x012A0DBC+2413564]
	GetHandleVerifier [0x010DD151+563089]
	GetHandleVerifier [0x010DBF13+558419]
	Ordinal0 [0x00FE081E+2164766]
	Ordinal0 [0x00FE5508+2184456]
	Ordinal0 [0x00FE5650+2184784]
	Ordinal0 [0x00FEF5BC+2225596]
	BaseThreadInitThunk [0x75C96739+25]
	RtlGetFullPathName_UEx [0x77AE8AFF+1215]
	RtlGetFullPathName_UEx [0x77AE8ACD+1165]

</p>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                Total: 12, Pass: 0, Error: 12 -- Duration: 79.30 s
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('td').on('click', '.btn', function(e){
                e.preventDefault();
                e.stopImmediatePropagation();
                var $this = $(this);
                var $nextRow = $this.closest('tr').next('tr');
                $nextRow.slideToggle("fast");
                $this.text(function(i, text){
                    if (text === 'View') {
                        return 'Hide';
                    } else {
                        return 'View';
                    };
                });
            });
        });
    </script>
</body>
</html